public class A{
	//...
	public static void main(){
		TreePath parent = event.getPath();
		//...
		Object obj2;
		//...
		if (cc.isDownloaded()&& !cc.hasChilds()&& !CheckableTree.this.isExpanded(parent.pathByAddingChild(obj2))) {
			//...
		}
	}
}