public class A{
	//...
	public static void main(){
		final int timeout = params.getConnectionTimeout();
		//...
		final Socket socket = socketfactory.createSocket();
		//...
		final SocketAddress remoteaddr = new InetSocketAddress(host, port);
		//...
		socket.connect(remoteaddr, timeout);
	}
}