public class A{
	//...
	public static void main(){
		int timeout = params.getConnectionTimeout();
		//...
		Socket socket = socketfactory.createSocket();
		//...
		SocketAddress remoteaddr = new InetSocketAddress(host, port);
		//...
		socket.connect(remoteaddr, timeout);
	}
}