public class A{
	//...
	public static void main(){
		Socket rval;
		//...
		int timeout = params.getConnectionTimeout();
		//...
		SocketAddress remoteaddr = new InetSocketAddress(host, port);
		//...
		rval.connect(remoteaddr, timeout);
	}
}